// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkiMjLbzH-pJ8_i0Lj6U9xlhLVIIxMzRQ',
    appId: '1:1068177468691:web:16f8d979451e411182fee6',
    messagingSenderId: '1068177468691',
    projectId: 'lexi-leap-app',
    authDomain: 'lexi-leap-app.firebaseapp.com',
    storageBucket: 'lexi-leap-app.appspot.com',
    measurementId: 'G-1Y16XLB0HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-ieZJ8EJfKYY21GnRut0m9QyXQb6Tkc',
    appId: '1:1068177468691:android:ef918e9ad1374f9f82fee6',
    messagingSenderId: '1068177468691',
    projectId: 'lexi-leap-app',
    storageBucket: 'lexi-leap-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWn1kTiG_82FbCleKXdtQSVJQvFoKbYU',
    appId: '1:1068177468691:ios:dafc8f9c1cc1604b82fee6',
    messagingSenderId: '1068177468691',
    projectId: 'lexi-leap-app',
    storageBucket: 'lexi-leap-app.appspot.com',
    iosBundleId: 'com.example.lexiLeap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWWn1kTiG_82FbCleKXdtQSVJQvFoKbYU',
    appId: '1:1068177468691:ios:dafc8f9c1cc1604b82fee6',
    messagingSenderId: '1068177468691',
    projectId: 'lexi-leap-app',
    storageBucket: 'lexi-leap-app.appspot.com',
    iosBundleId: 'com.example.lexiLeap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkiMjLbzH-pJ8_i0Lj6U9xlhLVIIxMzRQ',
    appId: '1:1068177468691:web:4261e0cf541a474382fee6',
    messagingSenderId: '1068177468691',
    projectId: 'lexi-leap-app',
    authDomain: 'lexi-leap-app.firebaseapp.com',
    storageBucket: 'lexi-leap-app.appspot.com',
    measurementId: 'G-S1B0HHEKWK',
  );
}
